services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habit_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=development
    networks:
      - habit-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habit_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - habit-network

networks:
  habit-network:
    driver: bridge